### PR TITLE
clarify usage of readr::problems() in read.quitte()

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**

### CODE REVIEW

**Review by chroetz — APPROVED** [review]
In interactive use, the warning is more helpful now. Thanks!
If `read.quitte()` is used in a script that writes warnings into a log file, we will not really see what went wrong exactly. But at least we will know that it is something related to `readr`.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
If you prefer, we can throw the entire problem data frame (or the first 8170 characters at least) into the log:
```
Warning message:
In read.quitte("/tmp/REMIND_generic_default-AMT-_withoutPlus.mif") :
  One or more parsing issues:
     row col expected actual                                             file
1  29915  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
2  29915  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
3  29915  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
4  30430  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
5  30430  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
6  30430  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
7  30879  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
8  30879  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
9  30879  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
10 31296  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
11 31296  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
12 31296  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
13 31680  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
14 31680  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
15 31680  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
16 32132  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
17 32132  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
18 32132  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
19 32627  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
20 32627  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
21 32627  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
22 33062  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
23 33062  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
24 33062  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
25 33535  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
26 33535  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
27 33535  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
28 34062  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
29 34062  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
30 34062  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
31 34544  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
32 34544  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
33 34544  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
34 35002  22 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
35 35002  23 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
36 35002  24 a number    Inf /tmp/REMIND_generic_default-AMT-_withoutPlus.mif
```
but keep the "look at `readr::problems()` not for interactive use.

**Comment by chroetz** [comment]
> If you prefer, we can throw the entire problem data frame (or the first 8170 characters at least) into the log:
> ...
> but keep the "look at readr::problems() not for interactive use.

Good idea! Showing the first n (e.g., n=3?) rows or something like that (why 8170 characters?) would help

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Warning message length has a hard cap at 8170 characters.  I guess a static 8k buffer minus space for adding `[... truncated]` and something.

**Review by chroetz — APPROVED** [review]
I tested it in interactive and non-interactive mode and it works without problems. Thanks @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q :)

**Pull request merged**
