### PR TITLE
add read.filter.snapshot() to load parts of big IIASA snapshots

### PR DESCRIPTION
**Pull request by orichters**
- IIASA database snapshots (csv files) easily reach several hundred MB (AR6 R5 regions only > 800 MB, NGFS REMIND only 380 MB)
- I can't load that directly into a quitte object without running out of memory
- often, you don't actually need all the data, but just parts of it, so this function pre-filters the data before loading it
- the new function gets a list `keep` of scenarios/regions… you want to keep
- it first creates a temporary file using `grep` that selects lines that are candidates for being kept, loads that into `R` and then does a proper filtering to cancel false positives
- the settings for `read.quitte` are specifically chosen to match the IIASA snapshot settings (quotes using `"`, empty cells mean `NA`)
- if you don't specify a `keep` argument, the whole file is loaded (obviously only works if the file is not too big), so you can use the snapshot settings for read.quitte alone

### CODE REVIEW

**Comment by orichters** [comment]
I think the `grep` works is not optimal. If I specify `list(scenario = "CurPol", region = "World")`, it first selects all lines containing either `,CurPol,` or `,World,` (or `;` instead of `,`) – while it would be better to only select those containing both. Thinking about it…

**Comment by orichters** [comment]
> I think the `grep` works is not optimal. If I specify `list(scenario = "CurPol", region = "World")`, it first selects all lines containing either `,CurPol,` or `,World,` (or `;` instead of `,`) – while it would be better to only select those containing both. Thinking about it…

Fixed that. I'm a bit more generous now with grepping to avoid that quoting or so cause problems. So `scenario = CurPol` will also match `CurPolWhatever`, but this will be sorted out in the `filter` part.

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — APPROVED** [review]
Do you need that in the package now?  I am asking for two reasons: I think it might be worthwhile to include this functionality in `read.quitte()` directly, instead of adding an extra function, and this implementation strictly speaking introduces system requirements for `head`, `grep`, and `tail`, which are not necessarily available for all users (not that I personally care :p).

**Comment by orichters** [comment]
No, I wrote it mainly for me to use it and I already do, so if we don't merge that into the package, that is not a problem for me at the moment. I doubt I would be the one to reimplement it, though.

**Pull request closed without merging**
