### PR TITLE
add is_quitte()

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
`is_quitte()` tests the minimal quitte "standard", that is: 
- `data.frame` class and 
- existence and class of `model`, `scenario`, `region`, `variable`, `unit`, `period`, and `value` columns.

### CODE REVIEW

**Comment by orichters** [comment]
- What is the difference between `is_quitte` and the old `is.quitte`? https://github.com/pik-piam/quitte/blob/master/R/is.quitte.R
- I find that a bit confusing…

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> What is the difference between `is_quitte` and the old `is.quitte`? https://github.com/pik-piam/quitte/blob/master/R/is.quitte.R

`is.quitte()` requires a `'quitte'` class attribute, and a bunch of columns to be of type `factor`, both of which are irrelevant for (most) `quitte` functions.

**Comment by fbenke-pik** [comment]
So i assume both helpers are needed in different contexts and should exist alongside? 
If not: I'd expect this to replace is.quitte.  If yes: You should reference the other function and point out differences between the two in the method signatures of both functions.

**Review by orichters — COMMENTED** [review]
> > What is the difference between `is_quitte` and the old `is.quitte`? https://github.com/pik-piam/quitte/blob/master/R/is.quitte.R
> 
> `is.quitte()` requires a `'quitte'` class attribute, and a bunch of columns to be of type `factor`, both of which are irrelevant for (most) `quitte` functions.

In piamInterfaces, we certainly have lots of of functions using `levels` that expect them to come as factors, but that is ok as the data goes through `as.quitte` before. I don't fully understand why a second "is quitte" function is useful and would probably have preferred something like `is.quitte(strict = FALSE)` or so to avoid having these 2 functions with basically the same name, but different behavior.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> In piamInterfaces, we certainly have lots of of functions using `levels` that expect them to come as factors

I was referring to functions within the `quitte` package.  Other packages are free to do whatever they want.  If you are bored some day and want to make that code more robust, have a look into `quitte::unique_or_levels()`.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
In the end I did not need that function now, so I will close this merge request.  I might open it again should I actually need it.

**Comment by orichters** [comment]
> I was referring to functions within the `quitte` package. Other packages are free to do whatever they want. If you are bored some day and want to make that code more robust, have a look into `quitte::unique_or_levels()`.

Good to know. But `as.quitte` guarantees factor columns, I think the code is as robust as needed ;)

**Pull request closed without merging**
