### PR TITLE
refactor calc_addVariable() to allow for overwriting existing variables

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
`reposearch` for `calc_addVariable` turned up 
- [x] `mredgebuildings::calcFloorspacePast()`
- [x] `mredgebuildings::calcFloorspacePast()`
- [x] `mredgebuildings::calcFloorspacePast()`
which gave identical results, and
- [ ] `Remind/scripts/output/comparison/Ariadne_output.R`
which breaks anyway on missing variables in the .mif files.

@fbenke-pik, I was referred to "Falk's Notebooks" when asking whether `Ariadne_output.R` is used for ARIADNE runs.  So you might want to test locally that they don't break with this update.

### CODE REVIEW

**Comment by fbenke-pik** [comment]
I am not sure what `Ariadne_output.R` is about.  Looks like it was created and used by @MariannaR.

I do use `calc_addVariable` quite a bit in my Ariadne scripts, though. Is it backwards-compatible? If it just breaks, I don't mind. I can fix that when it happens. I am more worried about subtle errors where nothing crashes but i get different numbers without noticing it.

**Comment by MariannaR** [comment]
Thanks @fbenke-pik for noticing. The file was included by myself but originally @fschreyer needed it - I am not sure if it is still to be kept, Felix? I actually never used it.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> I am more worried about subtle errors where nothing crashes but i get different numbers without noticing it.

Well, if it fails, it will either throw and error or return completely wrong numbers, but nothing subtle.
The row-order of the results is different then before, but I don't think that should effect anything.

**Review by fbenke-pik — APPROVED** [review]

**Review by robinhasse — COMMENTED** [review]
Thanks, Michaja 🙏

**Pull request merged**
